CREATE TABLE IF NOT EXISTS chat_log (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    request TEXT NOT NULL,
    response TEXT NOT NULL,
    timestamp TEXT NOT NULL,
    source TEXT NOT NULL,
    language TEXT NOT NULL,
    request_toxicity REAL,
    request_toxicity_openai REAL,
    request_toxicity_openai_explanation TEXT,
    request_sentiment REAL,
    request_sentiment_openai REAL,
    request_sentiment_openai_explanation TEXT,
    request_fluency REAL,
    request_fluency_openai REAL,
    request_fluency_openai_explanation TEXT,
    request_readability REAL,
    response_toxicity REAL,
    response_toxicity_openai REAL,
    response_toxicity_openai_explanation TEXT,
    response_sentiment REAL,
    response_sentiment_openai REAL,
    response_sentiment_openai_explanation TEXT,
    response_fluency REAL,
    response_fluency_openai REAL,
    response_fluency_openai_explanation TEXT,
    response_readability REAL,
    ai_disclaimer_similarity REAL,
    factual_consistency REAL,
    factual_consistency_openai REAL,
    factual_consistency_openai_explanation TEXT,
    completed BOOLEAN default 0
);
